### ISSUE TITLE
CLI not working

### ISSUE THREAD

**Issue by eggplants** [nandenjin/twinkle-parser#29]
From CLI:
```bash
~/twinkle-parser $ yarn run parse ../Downloads/kdb_20191114172106.csv 
yarn run v1.19.1
$ node dist/index.js ../Downloads/kdb_20191114172106.csv
module.js:549
    throw err;
    ^

Error: Cannot find module '/home/eggplants/twinkle-parser/dist/index.js'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
`/dist/` directory is missing. Please correct this probrem, or tell me how to fix it.
Thank you.

**Comment by nandenjin** [comment]
Thank you for your report! 

I just tried it with current code but it worked well. Maybe you missed step of install dependencies executed by `yarn install` command. Build step (generating `/dist`) will be automatically executed after installation.

```shell
# * Install dependencies (Build step automatically runs after this)
$ yarn install

# * Then try parsing again
$ yarn run parse PATH_TO_SRC
```

Please try `yarn install` at the root of the repo directory. If you even have same problem, please try manual build by `yarn build`. Sorry for unkind README, I will update it immediately.

**Comment by eggplants** [comment]
Thank you for your answer and kindness!
